version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config/
    ports:
      - "8390:80"

volumes:
  data:
  config:
